esphome:
  name: ac-controller-web
  friendly_name: Контроллер кондиционера

esp8266:
  board: nodemcuv2

ap:
  ssid: "AC-Controller-Setup"
  password: "password123"

captive_portal:

web_server:
  port: 80
  
ota:

remote_transmitter:
  pin: D2
  carrier_duty_percent: 50%

climate:
  - platform: template
    name: "Кондиционер LG"
    id: lg_konder
    lambda: |-
      it.protocol = "LG";
      it.publish_state();
    control_action:
      - remote_transmitter.transmit_lg:
          mode: !lambda return call.get_mode();
          temperature: !lambda return call.get_target_temperature();
