esphome:
  name: ac-controller-web
  friendly_name: Контроллер кондиционера

esp8266:
  board: nodemcuv2

ap:
  ssid: "AC-Controller-Setup"
  password: "password123"

captive_portal:

web_server:
  port: 80
  
ota:

remote_transmitter:
  pin: D2
  carrier_duty_percent: 50%

# ИСПОЛЬЗУЕМ СТАРЫЙ, НАДЕЖНЫЙ КОМПОНЕНТ
climate:
  - platform: ir_remote_climate
    name: "Кондиционер LG"
    protocol: LG
